version: '3.8'

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    ports:
      - "4444:80"  # <== map local port 4444 to Nginx port 80
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
